Hepsi:Derle Calistir
Derle:
	g++ -I ./include -c ./src/Dugum.cpp -o ./lib/Dugum.o
	g++ -I ./include -c ./src/Bst.cpp -o ./lib/Bst.o
	g++ -I ./include -c ./src/Islemler.cpp -o ./lib/Islemler.o
	g++ -I ./include -c ./src/Oyun.cpp -o ./lib/Oyun.o
	g++ -I ./include -c ./src/Main.cpp -o ./lib/Main.o
	g++ ./lib/Dugum.o ./lib/Bst.o ./lib/Islemler.o ./lib/Oyun.o ./lib/Main.o -o ./bin/calistir.exe
Calistir:
	./bin/calistir